//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialazerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int Id { get; set; }
        public string Motivo_de_visita { get; set; }
        public System.DateTime Fecha_de_visita { get; set; }
        public System.TimeSpan Hora_entrada { get; set; }
        public System.TimeSpan Hora_salidaa { get; set; }
        public string Nombre { get; set; }
        public string Contacto_que_lo_recibio { get; set; }
    }
}
